### PR TITLE
Fix `zig ar` command line too long issue on Windows

### PR DESCRIPTION
**Pull request by messense**
Try to reproduce https://github.com/messense/cargo-zigbuild/issues/52#issuecomment-1207139993

### CODE REVIEW

**Comment by messense** [comment]
> 'TARGET_OS_IPHONE' is not defined

Looks like https://github.com/ziglang/zig/issues/10377

**Comment by rtldg** [comment]
I forgot to add it immediately to the comment, but it was with `--target i686-pc-windows-gnu`.
msvc builds don't use `AR` I believe or something, so it probably won't show up in the CI because of that

**Comment by messense** [comment]
```
  AR_aarch64_unknown_linux_gnu = Some("C:\\Users\\runneradmin\\AppData\\Local\\cargo-zigbuild\\0.12.0-beta.1\\zigar.bat")
  running: "C:\\Users\\runneradmin\\AppData\\Local\\cargo-zigbuild\\0.12.0-beta.1\\zigar.bat" "cq" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-5972f6b30b5d989e\\out\\build\\libcurl.a" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-5972f6b30b5d989e\\out\\build\\curl/lib/asyn-thread.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-5972f6b30b5d989e\\out\\build\\curl/lib/altsvc.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-5972f6b30b5d989e\\out\\build\\curl/lib/base64.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-5972f6b30b5d989e\\out\\build\\curl/lib/bufref.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-lin...
  cargo:warning=The command line is too long.
  exit code: 1
```

Reproduced on Windows with `aarch64-unknown-linux-gnu` target.

**Comment by messense** [comment]
I think because `.bat` argument limit is 8191 chars while `.exe` limit is [32,768 UTF-16 codeunits](https://github.com/rust-lang/rust/issues/40384), since it's not exceeding the `.exe` limit, arguments are not passed via `@` file.

**Comment by messense** [comment]
```
running: "C:\\Users\\runneradmin\\AppData\\Local\\cargo-zigbuild\\0.12.0-beta.1\\ar.exe" "cq" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\libcurl.a" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/asyn-thread.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/altsvc.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/base64.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/bufref.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/conncache.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/connect.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/content_encoding.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/cookie.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/curl_addrinfo.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/curl_ctype.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/curl_get_line.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/curl_memrchr.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/curl_range.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/curl_threads.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/dotdot.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/doh.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/dynbuf.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/easy.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/escape.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/file.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/fileinfo.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/formdata.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/getenv.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/getinfo.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/hash.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/hmac.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/hostasyn.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/hostip.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/hostip6.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/hsts.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/http.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/http_aws_sigv4.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/http_chunks.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/http_digest.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/http_proxy.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/if2ip.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/inet_ntop.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/inet_pton.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/llist.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/md5.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/mime.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/mprintf.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/mqtt.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/multi.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/netrc.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/nonblock.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/parsedate.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/progress.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/rand.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/rename.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/select.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/sendf.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/setopt.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/sha256.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/share.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/slist.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/socks.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/socketpair.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/speedcheck.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/splay.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/strcase.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/strdup.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/strerror.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/strtok.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/strtoofft.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/timeval.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/transfer.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/url.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/urlapi.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/version.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/vauth/digest.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/vauth/vauth.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/vtls/hostcheck.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/vtls/keylog.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/vtls/vtls.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/warnless.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/wildcard.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/timediff.o" "D:\\a\\cargo-zigbuild\\cargo-zigbuild\\tests\\hello-rustls\\target\\aarch64-unknown-linux-gnu\\debug\\build\\curl-sys-239d360bed51338f\\out\\build\\curl/lib/vtls/rustls.o"
  cargo:warning=The command line is too long.
  exit code: 1
```

Unfortunately it still errors with `The command line is too long` using `ar.exe`.

**Comment by messense** [comment]
@calavera I had to remove `cmd.exe` to fix `The command line is too long` problem on Windows.

It now uses the `which` crate to find the absolute path to `zig`/`python`, hopefully it should still work, but it would be great to have some confirmations.

**Pull request merged**
